services:
  frontend:
    image: node:20-alpine
    container_name: frontend
    command: ["/bin/sh", "-c", "cd /usr/src/app && npm ci && npm run dev -- --host"]
    volumes:
      - ./client:/usr/src/app
    ports:
      - "5173:5173"
    networks:
      - Internal-Network
  server1:
    image: node:20-alpine
    container_name: server1
    command: ["/bin/sh", "-c", "cd /usr/src/app && npm ci && npx nodemon index.js"]
    volumes:
      - ./server:/usr/src/app
    networks:
      - Internal-Network
  server2:
    image: node:20-alpine
    container_name: server2
    command: ["/bin/sh", "-c", "cd /usr/src/app && npm ci && npx nodemon index.js"]
    volumes:
      - ./server2:/usr/src/app
    networks:
      - Internal-Network
    
networks:
  Internal-Network:
    name: Internal-Network
    external: false
